# Generated by Django 5.2.8 on 2025-11-19 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_social', models.CharField(help_text='Nome como a pessoa profissional deseja ser chamada', max_length=255)),
                ('profissao', models.CharField(help_text='Ex: Médica, Psicólogo, Enfermeira', max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('contato', models.CharField(help_text='Telefone ou e-mail', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(help_text='Data e hora da consulta')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.profissional')),
            ],
        ),
    ]
