"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
import dj_database_url


# Função para converter string para booleano
def str_to_bool(value):
    """Converte uma string comum ('true', '1', 'yes', 'false', '0') em booleano."""
    if value is None:
        return False
    return str(value).lower() in ('true', '1', 't', 'y', 'yes')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECRET_KEY: Leitura da variável de ambiente com fallback
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-chave-padrao-para-dev')

# DEBUG: Leitura da variável de ambiente
# Meu alerta: O DEBUG deve ser False em produção, mas True localmente
DEBUG = str_to_bool(os.environ.get('DEBUG', 'False'))



# 3. ALLOWED_HOSTS:

# Define ALLOWED_HOSTS como uma lista básica (sempre deve ser definida antes de usar append)
ALLOWED_HOSTS = [
    '127.0.0.1', # Loopback, usado pelo worker Gunicorn
    'localhost', # Para acesso local, se necessário
]

# Adiciona o Domínio Público do Elastic Beanstalk
eb_domain = os.environ.get('EB_DOMAIN_NAME')
if eb_domain:
    ALLOWED_HOSTS.append(eb_domain)

# Adiciona o IP Privado da instância EC2 (host Nginx)
eb_host_ip = os.environ.get('EB_HOST_IP')
if eb_host_ip:
    ALLOWED_HOSTS.append(eb_host_ip)
    
# Se DEBUG for True, adiciona o curinga para facilitar o desenvolvimento local/staging
if DEBUG:
    ALLOWED_HOSTS.append('*')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Terceiros
    'corsheaders',
    'rest_framework',
    'django_filters',
    'rest_framework_simplejwt', # 🔑 Adicionado o app para JWT
    # Apps do Projeto
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuração do Banco de Dados
DATABASES = {
    'default': dj_database_url.config(
        # Procura por uma variável chamada DATABASE_URL
        default=os.environ.get('DATABASE_URL', 'sqlite:///db.sqlite3'), 
        conn_max_age=600,
        # Configurações para conexões persistentes
        ssl_require=str_to_bool(os.environ.get('DB_SSL_REQUIRED', 'False'))
        )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br' 

TIME_ZONE = 'America/Sao_Paulo' 

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' 

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST FRAMEWORK & JWT SETTINGS

REST_FRAMEWORK = {
    # Configura o filtro global
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    
    # --- Configuração de Autenticação ---
    
    # Define que o JWT para ler a key
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    
    # Define a permissão padrão: "obs: Só acessa quem estiver autenticado"
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Configurações do DRF Simple JWT
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY, # Usa a mesma chave secreta do Django
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
}


# LOGGING
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # Log geral do Django
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        # Log específico de requisições (HTTP 200, 400, 500)
        'django.request': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# CORS
# Permitir que qualquer origem acesse a API
CORS_ALLOW_ALL_ORIGINS = True